Main.o: Main.cpp ShaderProgram.h Matrix4.h Vector4.h Matrix3.h Vector3.h \
 KeyBuffer.h Scene.h ModelController.h Model.h Transform.h Camera.h \
 Mesh.h Texture.h Frustum.h Animation.h Quaternion.h Material.h \
 MeshNode.h Debug.h LightCollection.h MouseBuffer.h

ShaderProgram.h:

Matrix4.h:

Vector4.h:

Matrix3.h:

Vector3.h:

KeyBuffer.h:

Scene.h:

ModelController.h:

Model.h:

Transform.h:

Camera.h:

Mesh.h:

Texture.h:

Frustum.h:

Animation.h:

Quaternion.h:

Material.h:

MeshNode.h:

Debug.h:

LightCollection.h:

MouseBuffer.h:
Math.o: Math.cpp Math.h Vector3.h

Math.h:

Vector3.h:
Vector3.o: Vector3.cpp Vector3.h Math.h

Vector3.h:

Math.h:
Vector4.o: Vector4.cpp Vector4.h

Vector4.h:
Matrix3.o: Matrix3.cpp Matrix3.h Vector3.h Math.h

Matrix3.h:

Vector3.h:

Math.h:
Matrix4.o: Matrix4.cpp Math.h Vector3.h Matrix4.h Vector4.h

Math.h:

Vector3.h:

Matrix4.h:

Vector4.h:
Transform.o: Transform.cpp Math.h Vector3.h Transform.h Matrix4.h \
 Vector4.h Matrix3.h

Math.h:

Vector3.h:

Transform.h:

Matrix4.h:

Vector4.h:

Matrix3.h:
Animation.o: Animation.cpp Animation.h ShaderProgram.h Matrix4.h \
 Vector4.h Matrix3.h Vector3.h Transform.h Quaternion.h

Animation.h:

ShaderProgram.h:

Matrix4.h:

Vector4.h:

Matrix3.h:

Vector3.h:

Transform.h:

Quaternion.h:
Material.o: Material.cpp Material.h Vector3.h ShaderProgram.h Matrix4.h \
 Vector4.h Matrix3.h

Material.h:

Vector3.h:

ShaderProgram.h:

Matrix4.h:

Vector4.h:

Matrix3.h:
LightCollection.o: LightCollection.cpp LightCollection.h ShaderProgram.h \
 Matrix4.h Vector4.h Matrix3.h Vector3.h Camera.h Transform.h

LightCollection.h:

ShaderProgram.h:

Matrix4.h:

Vector4.h:

Matrix3.h:

Vector3.h:

Camera.h:

Transform.h:
ShaderProgram.o: ShaderProgram.cpp ShaderProgram.h Matrix4.h Vector4.h \
 Matrix3.h Vector3.h

ShaderProgram.h:

Matrix4.h:

Vector4.h:

Matrix3.h:

Vector3.h:
Camera.o: Camera.cpp Camera.h Transform.h Matrix4.h Vector4.h Matrix3.h \
 Vector3.h ShaderProgram.h Math.h

Camera.h:

Transform.h:

Matrix4.h:

Vector4.h:

Matrix3.h:

Vector3.h:

ShaderProgram.h:

Math.h:
KeyBuffer.o: KeyBuffer.cpp KeyBuffer.h

KeyBuffer.h:
MouseBuffer.o: MouseBuffer.cpp MouseBuffer.h

MouseBuffer.h:
Scene.o: Scene.cpp Scene.h ModelController.h Model.h Transform.h \
 Matrix4.h Vector4.h Matrix3.h Vector3.h Camera.h ShaderProgram.h Mesh.h \
 Texture.h Frustum.h Animation.h Quaternion.h Material.h MeshNode.h \
 Debug.h LightCollection.h MouseBuffer.h Math.h

Scene.h:

ModelController.h:

Model.h:

Transform.h:

Matrix4.h:

Vector4.h:

Matrix3.h:

Vector3.h:

Camera.h:

ShaderProgram.h:

Mesh.h:

Texture.h:

Frustum.h:

Animation.h:

Quaternion.h:

Material.h:

MeshNode.h:

Debug.h:

LightCollection.h:

MouseBuffer.h:

Math.h:
Texture.o: Texture.cpp Texture.h ShaderProgram.h Matrix4.h Vector4.h \
 Matrix3.h Vector3.h

Texture.h:

ShaderProgram.h:

Matrix4.h:

Vector4.h:

Matrix3.h:

Vector3.h:
ModelController.o: ModelController.cpp ModelController.h Model.h \
 Transform.h Matrix4.h Vector4.h Matrix3.h Vector3.h Camera.h \
 ShaderProgram.h Mesh.h Texture.h Frustum.h Animation.h Quaternion.h \
 Material.h MeshNode.h Debug.h

ModelController.h:

Model.h:

Transform.h:

Matrix4.h:

Vector4.h:

Matrix3.h:

Vector3.h:

Camera.h:

ShaderProgram.h:

Mesh.h:

Texture.h:

Frustum.h:

Animation.h:

Quaternion.h:

Material.h:

MeshNode.h:

Debug.h:
Model.o: Model.cpp Model.h Transform.h Matrix4.h Vector4.h Matrix3.h \
 Vector3.h Camera.h ShaderProgram.h Mesh.h Texture.h Frustum.h \
 Animation.h Quaternion.h Material.h MeshNode.h Debug.h AiScene.h

Model.h:

Transform.h:

Matrix4.h:

Vector4.h:

Matrix3.h:

Vector3.h:

Camera.h:

ShaderProgram.h:

Mesh.h:

Texture.h:

Frustum.h:

Animation.h:

Quaternion.h:

Material.h:

MeshNode.h:

Debug.h:

AiScene.h:
Mesh.o: Mesh.cpp Mesh.h Texture.h ShaderProgram.h Matrix4.h Vector4.h \
 Matrix3.h Vector3.h Frustum.h

Mesh.h:

Texture.h:

ShaderProgram.h:

Matrix4.h:

Vector4.h:

Matrix3.h:

Vector3.h:

Frustum.h:
MeshNode.o: MeshNode.cpp MeshNode.h Mesh.h Texture.h ShaderProgram.h \
 Matrix4.h Vector4.h Matrix3.h Vector3.h Frustum.h Camera.h Transform.h \
 Debug.h Material.h

MeshNode.h:

Mesh.h:

Texture.h:

ShaderProgram.h:

Matrix4.h:

Vector4.h:

Matrix3.h:

Vector3.h:

Frustum.h:

Camera.h:

Transform.h:

Debug.h:

Material.h:
Frustum.o: Frustum.cpp Frustum.h Vector3.h Matrix4.h Vector4.h Matrix3.h

Frustum.h:

Vector3.h:

Matrix4.h:

Vector4.h:

Matrix3.h:
Debug.o: Debug.cpp Debug.h Frustum.h Vector3.h Matrix4.h Vector4.h \
 Matrix3.h Transform.h ShaderProgram.h Mesh.h Texture.h Material.h \
 AiScene.h MeshNode.h Camera.h Animation.h Quaternion.h

Debug.h:

Frustum.h:

Vector3.h:

Matrix4.h:

Vector4.h:

Matrix3.h:

Transform.h:

ShaderProgram.h:

Mesh.h:

Texture.h:

Material.h:

AiScene.h:

MeshNode.h:

Camera.h:

Animation.h:

Quaternion.h:
AiScene.o: AiScene.cpp AiScene.h Mesh.h Texture.h ShaderProgram.h \
 Matrix4.h Vector4.h Matrix3.h Vector3.h Frustum.h MeshNode.h Camera.h \
 Transform.h Debug.h Material.h Animation.h Quaternion.h

AiScene.h:

Mesh.h:

Texture.h:

ShaderProgram.h:

Matrix4.h:

Vector4.h:

Matrix3.h:

Vector3.h:

Frustum.h:

MeshNode.h:

Camera.h:

Transform.h:

Debug.h:

Material.h:

Animation.h:

Quaternion.h:
